spring:
  application:
    name: user_service
  profiles:
    active: dev
#  security:
#    user:
#      name: mee
#      password: "{noop}metoo"

server:
  port: 8070
  servlet:
    context-path: /user-service/api/v1




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka-server/api/v1/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10      # send heartbeat every 10 seconds
    lease-expiration-duration-in-seconds: 30
    hostname: localhost

