spring:
  application:
    name: user_service
  profiles:
    active: dev

server:
  port: 8070

#eureka:
#  client:
#    enabled: false
#    service-url:
#      defaultZone: http://localhost:8090/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
