spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: fitness_user_admin
    password: fitness_user_admin_123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
